name = "backend"
compatibility_date = "2024-08-07"

# [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNDEwOTI0ZjItOWZkYy00Njg4LTlmMjItNWYxNmNiMzUzYmM3IiwidGVuYW50X2lkIjoiNWY0NTkzMWU1YjI4OTRjMzZlMGZjNzljZjk5ZWU0OTllYjI3ZmRlMjE4NGMyYzJhYTBjNmFiOTQ4ZWVmZTcwMiIsImludGVybmFsX3NlY3JldCI6ImYyZTA0MTM5LWRkYzMtNDA0Yy04ODAxLTQwNzM0MWI0OWYxMCJ9.vBKEwY2RTNtGbPM9bZEyQfLq8SwLNL7UYgU1ZHVPSBI"